@HospitalManagement.Api_HostAddress = http://localhost:5253

###
POST http://localhost:5253/register
Content-Type: application/json

{
    "Email": "maluva@gmail.com",
    "Initials": "ms",
    "Password": "Danuj#20501"
}

###
POST  http://localhost:5253/login
Content-Type: application/json

{
    "Email": "senanayakakethaka@gmail.com",
    "Password": "Danuj#20501"
}

###
POST  http://localhost:5253/login
Content-Type: application/json

{
    "Email": "rilava@gmail.com",
    "Password": "Danuj#20501"
}

###
PUT http://localhost:5253/appointments/3031/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWI1M2UwZS05OTA3LTQzZTItYWM3ZS1kNzljYmY4NWI1YzEiLCJlbWFpbCI6InNlbmFuYXlha2FrZXRoYWthQGdtYWlsLmNvbSIsIm5hbWUiOiJrcyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZDFiNTNlMGUtOTkwNy00M2UyLWFjN2UtZDc5Y2JmODViNWMxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic2VuYW5heWFrYWtldGhha2FAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJleHAiOjE3Nzc4MTkzNTMsImlhdCI6MTc3NzgxOTIzMywibmJmIjoxNzc3ODE5MjMzfQ.3ltvFzU1c0SaHsiQSne8r3eE7llljlaq6n4NwndnOxI

{
  "status": "Rejected"
}

###
GET http://localhost:5253/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWI1M2UwZS05OTA3LTQzZTItYWM3ZS1kNzljYmY4NWI1YzEiLCJlbWFpbCI6InNlbmFuYXlha2FrZXRoYWthQGdtYWlsLmNvbSIsIm5hbWUiOiJrcyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZDFiNTNlMGUtOTkwNy00M2UyLWFjN2UtZDc5Y2JmODViNWMxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic2VuYW5heWFrYWtldGhha2FAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJleHAiOjE3Nzc2MjA0NTgsImlhdCI6MTc3NzYyMDMzOCwibmJmIjoxNzc3NjIwMzM4fQ.TuU-6R2IbJlLOsmgtJcMDPHzEpjfo8d72QMTDBcwvKE

###
GET http://localhost:5253/users/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWI1M2UwZS05OTA3LTQzZTItYWM3ZS1kNzljYmY4NWI1YzEiLCJlbWFpbCI6InNlbmFuYXlha2FrZXRoYWthQGdtYWlsLmNvbSIsIm5hbWUiOiJrcyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZDFiNTNlMGUtOTkwNy00M2UyLWFjN2UtZDc5Y2JmODViNWMxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic2VuYW5heWFrYWtldGhha2FAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJleHAiOjE3NzgyMzY3MDQsImlhdCI6MTc3ODIzNjU4NSwibmJmIjoxNzc4MjM2NTg1fQ.IuP_phPtiN_CGLTpKgQEH7CYJqUAJBm7Id5ICeovKUo
###
Get http://localhost:5253/appointments/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWI1M2UwZS05OTA3LTQzZTItYWM3ZS1kNzljYmY4NWI1YzEiLCJlbWFpbCI6InNlbmFuYXlha2FrZXRoYWthQGdtYWlsLmNvbSIsIm5hbWUiOiJrcyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZDFiNTNlMGUtOTkwNy00M2UyLWFjN2UtZDc5Y2JmODViNWMxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic2VuYW5heWFrYWtldGhha2FAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJleHAiOjE3Nzc5MTA1MDcsImlhdCI6MTc3NzkxMDM4NywibmJmIjoxNzc3OTEwMzg3fQ.wlCCoLWvQvxriNbtEb0Dzu8tBa-Zvb5jf1Ig8pr0vNc

###
POST http://localhost:5253/medical-records
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWI1M2UwZS05OTA3LTQzZTItYWM3ZS1kNzljYmY4NWI1YzEiLCJlbWFpbCI6InNlbmFuYXlha2FrZXRoYWthQGdtYWlsLmNvbSIsIm5hbWUiOiJrcyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZDFiNTNlMGUtOTkwNy00M2UyLWFjN2UtZDc5Y2JmODViNWMxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic2VuYW5heWFrYWtldGhha2FAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJleHAiOjE3NzgxNjgwODUsImlhdCI6MTc3ODE2Nzk2NSwibmJmIjoxNzc4MTY3OTY1fQ.UEk9bEvcFSqhAVJ0_wEcaBj_bNJZa3cyOPZcLojByqU

{
  "userId": "cffdfb6f-bb59-44ab-997f-b1e9c02fbff1",
  "title": "Blood Test Report 2",
  "description": "Patient has high sugar levels and blood pressure."
}

###
GET http://localhost:5253/medical-records
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZmZkZmI2Zi1iYjU5LTQ0YWItOTk3Zi1iMWU5YzAyZmJmZjEiLCJlbWFpbCI6InJpbGF2YUBnbWFpbC5jb20iLCJuYW1lIjoiZGFudWoiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImNmZmRmYjZmLWJiNTktNDRhYi05OTdmLWIxZTljMDJmYmZmMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InJpbGF2YUBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJNZW1iZXIiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJleHAiOjE3NzgxNjgyMTUsImlhdCI6MTc3ODE2ODA5NSwibmJmIjoxNzc4MTY4MDk1fQ.uQ-u-3GEBnOJfBKyFbguxyIXOKfPvl9XMhKL1HlK0M8

###
GET http://localhost:5253/medical-records/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWI1M2UwZS05OTA3LTQzZTItYWM3ZS1kNzljYmY4NWI1YzEiLCJlbWFpbCI6InNlbmFuYXlha2FrZXRoYWthQGdtYWlsLmNvbSIsIm5hbWUiOiJrcyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZDFiNTNlMGUtOTkwNy00M2UyLWFjN2UtZDc5Y2JmODViNWMxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic2VuYW5heWFrYWtldGhha2FAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJleHAiOjE3NzgxNjc4MDEsImlhdCI6MTc3ODE2NzY4MSwibmJmIjoxNzc4MTY3NjgxfQ.KVviITSzLJRYaRy0CHpEFCNwCwzHSPFbL-4pT3vz870

###
POST http://localhost:5253/bills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWI1M2UwZS05OTA3LTQzZTItYWM3ZS1kNzljYmY4NWI1YzEiLCJlbWFpbCI6InNlbmFuYXlha2FrZXRoYWthQGdtYWlsLmNvbSIsIm5hbWUiOiJrcyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZDFiNTNlMGUtOTkwNy00M2UyLWFjN2UtZDc5Y2JmODViNWMxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic2VuYW5heWFrYWtldGhha2FAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJleHAiOjE3NzgyMzcxNzAsImlhdCI6MTc3ODIzNzA1MCwibmJmIjoxNzc4MjM3MDUwfQ.v91iUZZ2B3T4al0pVvWkBqFjsI6eu1kcBZDgxNve-kM

{
  "userId": "cffdfb6f-bb59-44ab-997f-b1e9c02fbff1",
  "title": "Hospital Consultation Fee",
  "amount": 15000
}

###
GET http://localhost:5253/bills
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZmZkZmI2Zi1iYjU5LTQ0YWItOTk3Zi1iMWU5YzAyZmJmZjEiLCJlbWFpbCI6InJpbGF2YUBnbWFpbC5jb20iLCJuYW1lIjoiZGFudWoiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImNmZmRmYjZmLWJiNTktNDRhYi05OTdmLWIxZTljMDJmYmZmMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InJpbGF2YUBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJNZW1iZXIiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJleHAiOjE3NzgyMzczOTcsImlhdCI6MTc3ODIzNzI3NywibmJmIjoxNzc4MjM3Mjc3fQ.X7h_rx88FJL5VP82iRtToat2ixLQHL8eUxHODeU7cPY

###
GET http://localhost:5253/bills/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWI1M2UwZS05OTA3LTQzZTItYWM3ZS1kNzljYmY4NWI1YzEiLCJlbWFpbCI6InNlbmFuYXlha2FrZXRoYWthQGdtYWlsLmNvbSIsIm5hbWUiOiJrcyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZDFiNTNlMGUtOTkwNy00M2UyLWFjN2UtZDc5Y2JmODViNWMxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic2VuYW5heWFrYWtldGhha2FAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJleHAiOjE3NzgyMzc0MzksImlhdCI6MTc3ODIzNzMxOSwibmJmIjoxNzc4MjM3MzE5fQ.ghmoYqCphEXbPQ1HrUvR5ON1r-jwVeUijklv7h8LZqQ

###
POST http://localhost:5253/labresults
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWI1M2UwZS05OTA3LTQzZTItYWM3ZS1kNzljYmY4NWI1YzEiLCJlbWFpbCI6InNlbmFuYXlha2FrZXRoYWthQGdtYWlsLmNvbSIsIm5hbWUiOiJrcyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZDFiNTNlMGUtOTkwNy00M2UyLWFjN2UtZDc5Y2JmODViNWMxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic2VuYW5heWFrYWtldGhha2FAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJleHAiOjE3NzgzMTAwOTIsImlhdCI6MTc3ODMwOTk3MiwibmJmIjoxNzc4MzA5OTcyfQ.Rs30mz3W5LsAPLV4fgpPk6BPcf4maI0SujzPbjrFIYM
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="UserId"

cffdfb6f-bb59-44ab-997f-b1e9c02fbff1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Title"

Blood Test Report
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="ResultText"

Sugar level slightly high, cholesterol normal
------WebKitFormBoundary7MA4YWxkTrZu0gW--