@HospitalManagement.Api_HostAddress = http://localhost:5253

###
POST http://localhost:5253/register
Content-Type: application/json

{
    "Email": "danujkethaka@gmail.com",
    "Initials": "dk",
    "Password": "Danuj#20501"
}

###
POST  http://localhost:5253/login
Content-Type: application/json

{
    "Email": "senanayakakethaka@gmail.com",
    "Password": "Danuj#20501"
}

###
POST http://localhost:5253/appointments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWI1M2UwZS05OTA3LTQzZTItYWM3ZS1kNzljYmY4NWI1YzEiLCJlbWFpbCI6InNlbmFuYXlha2FrZXRoYWthQGdtYWlsLmNvbSIsIm5hbWUiOiJrcyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZDFiNTNlMGUtOTkwNy00M2UyLWFjN2UtZDc5Y2JmODViNWMxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic2VuYW5heWFrYWtldGhha2FAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJleHAiOjE3Nzc2NDc5NDcsImlhdCI6MTc3NzY0NzgyNywibmJmIjoxNzc3NjQ3ODI3fQ.0WUnlkgSRDO3o081s2jFQHr_d67T4ZTB8lcwd7YyxpU

{
  "doctoreName": "Dr. Kethaka Senanayaka",
  "departmentName": "Sex department",
  "dateTime": "2026-03-27T10:30:00"
}

###
GET http://localhost:5253/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWI1M2UwZS05OTA3LTQzZTItYWM3ZS1kNzljYmY4NWI1YzEiLCJlbWFpbCI6InNlbmFuYXlha2FrZXRoYWthQGdtYWlsLmNvbSIsIm5hbWUiOiJrcyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZDFiNTNlMGUtOTkwNy00M2UyLWFjN2UtZDc5Y2JmODViNWMxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic2VuYW5heWFrYWtldGhha2FAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJleHAiOjE3Nzc2MjA0NTgsImlhdCI6MTc3NzYyMDMzOCwibmJmIjoxNzc3NjIwMzM4fQ.TuU-6R2IbJlLOsmgtJcMDPHzEpjfo8d72QMTDBcwvKE

###
GET http://localhost:5253/users/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWI1M2UwZS05OTA3LTQzZTItYWM3ZS1kNzljYmY4NWI1YzEiLCJlbWFpbCI6InNlbmFuYXlha2FrZXRoYWthQGdtYWlsLmNvbSIsIm5hbWUiOiJrcyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZDFiNTNlMGUtOTkwNy00M2UyLWFjN2UtZDc5Y2JmODViNWMxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic2VuYW5heWFrYWtldGhha2FAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJleHAiOjE3Nzc2MjA5NDksImlhdCI6MTc3NzYyMDgyOSwibmJmIjoxNzc3NjIwODI5fQ.c-a4dec93LJzx1A01CmxDMO7dBgJUZQf3XVSLKu8jNw

###
Get http://localhost:5253/appointments/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWI1M2UwZS05OTA3LTQzZTItYWM3ZS1kNzljYmY4NWI1YzEiLCJlbWFpbCI6InNlbmFuYXlha2FrZXRoYWthQGdtYWlsLmNvbSIsIm5hbWUiOiJrcyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZDFiNTNlMGUtOTkwNy00M2UyLWFjN2UtZDc5Y2JmODViNWMxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoic2VuYW5heWFrYWtldGhha2FAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUyNTMiLCJleHAiOjE3Nzc2NDc5OTgsImlhdCI6MTc3NzY0Nzg3OCwibmJmIjoxNzc3NjQ3ODc4fQ.-A3bXWjIBEDAEO4WiGP4VUETzD73ZUlRyY46gFr-QcI